export const paths = {
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  knowledges: '/knowledges',
  knowledgeNew: '/knowledges/new',
  knowledgeEdit: (id: string) => `/knowledges/${id}`,
  categories: '/categories',
  tags: '/tags',
  questions: '/questions',
  questionNew: '/questions/new',
  questionEdit: (id: string) => `/questions/${id}`,
  collections: '/collections',
  collectionNew: '/collections/new',
  collectionEdit: (id: string) => `/collections/${id}`,
  contents: '/contents',
  contentNew: '/contents/new',
  contentEdit: (id: string) => `/contents/${id}`,
  exams: '/exams',
  examNew: '/exams/new',
  examEdit: (id: string) => `/exams/${id}`,
  examTake: (id: string) => `/exam-records/${id}`,
} as const;
